#-------------------------------------------------------------------------------
# Copyright (C) 2017 Create-Net / FBK.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Create-Net / FBK - initial API and implementation
#-------------------------------------------------------------------------------
language: node_js
node_js:
  - "7"

env:
  global:
    - COMPONENT=agile-stack
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - VERSIONIST=true

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)

after_success:
  - versionist_if_needed
