version: '2'

services:
    agile-core:
      image: agileiot/agile-core-$ARCH
      volumes:
        - $DBUS_SYSTEM_SOCKET:/var/run/dbus/system_bus_socket
        - $DBUS_SESSION_SOCKET:/usr/src/app/agile_bus_socket
      environment:
        - DBUS_SESSION_BUS_ADDRESS=unix:path=/usr/src/app/agile_bus_socket
      ports:
        - 8081:8081/tcp
        - 8080:8080/tcp
      restart: always
      privileged: true

    agile-ui:
      image: craycraig/agile-ui-armv7l
      environment:
        - AGILE_CLIENT_PORT=$AGILE_CLIENT_PORT
      ports:
        - $AGILE_CLIENT_PORT:$AGILE_CLIENT_PORT
      restart: always
